// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaEY3I6g-RN1gBVutwTllawvqxDZfLhRY',
    appId: '1:478295814840:web:ae6cfa86bf01964f34fa4d',
    messagingSenderId: '478295814840',
    projectId: 'atcnewsapp',
    authDomain: 'atcnewsapp.firebaseapp.com',
    storageBucket: 'atcnewsapp.appspot.com',
    measurementId: 'G-4THW8BW95M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3m7sWCEoeUBxWVcQqdjrtBxEO3t0Mv8',
    appId: '1:478295814840:android:0dcdc1522326afb634fa4d',
    messagingSenderId: '478295814840',
    projectId: 'atcnewsapp',
    storageBucket: 'atcnewsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNnOL_ghZgezHyYklWP7gumSXrJtimS3o',
    appId: '1:478295814840:ios:26540a1f0053f6a634fa4d',
    messagingSenderId: '478295814840',
    projectId: 'atcnewsapp',
    storageBucket: 'atcnewsapp.appspot.com',
    iosBundleId: 'com.example.newsAndForums',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNnOL_ghZgezHyYklWP7gumSXrJtimS3o',
    appId: '1:478295814840:ios:26540a1f0053f6a634fa4d',
    messagingSenderId: '478295814840',
    projectId: 'atcnewsapp',
    storageBucket: 'atcnewsapp.appspot.com',
    iosBundleId: 'com.example.newsAndForums',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaEY3I6g-RN1gBVutwTllawvqxDZfLhRY',
    appId: '1:478295814840:web:ec60d7d1e36c25b134fa4d',
    messagingSenderId: '478295814840',
    projectId: 'atcnewsapp',
    authDomain: 'atcnewsapp.firebaseapp.com',
    storageBucket: 'atcnewsapp.appspot.com',
    measurementId: 'G-TDCCPLVSGN',
  );
}
